### ISSUE TITLE
Genres api is not working!

### ISSUE THREAD

**Issue by sairamc** [maxehmookau/echonest-ruby-api#42]
song = Echonest::Song.new('YOUR-API-KEY') and
artist = Echonest::Artist.new('YOUR-API-KEY', 'Weezer') are working fine

But when you try to access genre using
genre = Echonest::Genre.new('YOUR-API-KEY', 'folk rock')
it's giving the following exception:
NameError Exception: uninitialized constant Echonest::Genre

**Comment by maxehmookau** [comment]
Could you give a bit more information about what it is you're trying to do? I can have a look when I get time but if you want a speedy resolution I suggest writing a failing test and pull requesting it with a fix.

Thanks :)
