### ISSUE TITLE
Please release 0.8.0

### ISSUE THREAD

**Issue by xdmx** [maxehmookau/echonest-ruby-api#44]
It's been almost 1 year since the 0.7.0 release and there have been various new commits in the repo. It'd be nice to have them in a new release (0.8.0?) in order to avoid to have to fetch the repository (which has an astonishing size of almost 40mb versus few KBs of the gem)

**Comment by maxehmookau** [comment]
You're absolutely right, I'm very sorry.

The gem files are on my laptop, I'll aim to release tomorrow. I'm adding a reminder to my phone right now.

**Comment by maxehmookau** [comment]
Done. Just pushed it to rubygems :) as `0.8.0`

**Comment by xdmx** [comment]
Thank you!

**Comment by maxehmookau** [comment]
No problem :) Sorry it took so long!
